`timescale 1ns / 1ps

// -----------------------------------------------------------------------------
// Vendor provided FFT IP core declaration
// Replace this stub with the actual IP instantiation generated by the FPGA tool.
// -----------------------------------------------------------------------------
module fft_ip_core_stub #(
    parameter integer DATA_WIDTH  = 16,
    parameter integer POINTS      = 1024
) (
    input  wire                   aclk,
    input  wire                   aresetn,
    // AXI-Stream input (time-domain samples)
    input  wire [DATA_WIDTH-1:0]  s_axis_tdata,
    input  wire                   s_axis_tvalid,
    output wire                   s_axis_tready,
    input  wire                   s_axis_tlast,
    // AXI-Stream output (frequency-domain bins)
    output wire [2*DATA_WIDTH-1:0] m_axis_tdata,
    output wire                    m_axis_tvalid,
    input  wire                    m_axis_tready,
    output wire                    m_axis_tlast
);
    // synthesis translate_off
    assign s_axis_tready = 1'b1;
    assign m_axis_tdata  = {2*DATA_WIDTH{1'b0}};
    assign m_axis_tvalid = 1'b0;
    assign m_axis_tlast  = 1'b0;
    // synthesis translate_on
endmodule
